spring:
  port: 8080
  application:
    name: test
  rabbitmq:
    host: 140.143.136.212
    port: 5672
    username: guest
    password: guest
    virtualHost: /
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual



